// QSkyway — FAA UAS Facility Map airspace ceilings over the NYC twin.
// Generated by scripts/fetch-faa-airspace.mjs 2026-07-26. Do not edit by hand.
//
// Real regulator-published data (FAA UASFM, open ArcGIS feed, no key). CEILING is
// the maximum altitude AGL at which small-UAS flight is automatically authorizable
// (LAANC) in that cell; 0 ft means no automatic authorization — ATC coordination
// required. This is a Part 107 small-UAS grid, NOT eVTOL air-taxi certification;
// QSkyway uses it as the authoritative altitude-constraint layer and says so.
/* eslint-disable */
import type { CityAirspace } from "./qskyway.airspace";

export const AIRSPACE_NYC: CityAirspace = {
  "source": "FAA UAS Facility Map (UASFM)",
  "sourceUrl": "https://services6.arcgis.com/ssFJjBXIUyZDrSYZ/arcgis/rest/services/FAA_UAS_FacilityMap_Data/FeatureServer/0",
  "authority": "FAA",
  "regime": "Part 107 small-UAS LAANC authorization ceilings",
  "effective": "7/9/2026",
  "fetched": "2026-07-26",
  "bbox": {
    "minLat": 40.7474728,
    "maxLat": 40.7629936,
    "minLon": -74.0002478,
    "maxLon": -73.9758674
  },
  "cells": [
    {
      "id": "faa-148561",
      "minLon": -74.0000059,
      "maxLon": -73.9916726,
      "minLat": 40.7416735,
      "maxLat": 40.7500068,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-148559",
      "minLon": -73.9916726,
      "maxLon": -73.9833393,
      "minLat": 40.7416735,
      "maxLat": 40.7500068,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-148557",
      "minLon": -73.9833393,
      "maxLon": -73.9750059,
      "minLat": 40.7416735,
      "maxLat": 40.7500068,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-148720",
      "minLon": -74.0000059,
      "maxLon": -73.9916726,
      "minLat": 40.7500068,
      "maxLat": 40.7583401,
      "ceilingFt": 0,
      "ceilingM": 0,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-311810",
      "minLon": -73.9916726,
      "maxLon": -73.9833393,
      "minLat": 40.7500068,
      "maxLat": 40.7583401,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-148732",
      "minLon": -73.9833393,
      "maxLon": -73.9750059,
      "minLat": 40.7500068,
      "maxLat": 40.7583401,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-148895",
      "minLon": -74.0000059,
      "maxLon": -73.9916726,
      "minLat": 40.7583401,
      "maxLat": 40.7666735,
      "ceilingFt": 0,
      "ceilingM": 0,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-311812",
      "minLon": -73.9916726,
      "maxLon": -73.9833393,
      "minLat": 40.7583401,
      "maxLat": 40.7666735,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    },
    {
      "id": "faa-148908",
      "minLon": -73.9833393,
      "maxLon": -73.9750059,
      "minLat": 40.7583401,
      "maxLat": 40.7666735,
      "ceilingFt": 400,
      "ceilingM": 122,
      "airspaceClass": "B",
      "airportIcao": "KLGA",
      "airportName": "Laguardia",
      "laanc": true,
      "effective": "7/9/2026"
    }
  ]
};
