// QSkyway — MLIT/JCAB permission regime over the TOKYO twin.
// Generated by scripts/sample-did-permission.mjs 2026-07-26. Do not edit by hand.
//
// Real regulator-published data, but a DIFFERENT KIND of rule from the FAA
// ceiling grid: a gate on whether the flight may happen at all, not a limit on
// its altitude. Kept in its own type for exactly that reason.
//
// Provenance is "raster-sampled", not "ingested": Japan publishes this layer as
// map tiles, so the value below is a faithful reading of the authority's own
// rendering at our grid-cell centres — not a vector dataset we were handed.
/* eslint-disable */
import type { CityPermission } from "./qskyway.permission";

export const PERMISSION_TOKYO: CityPermission = {
  "authority": "MLIT / JCAB",
  "source": "Densely Inhabited District (人口集中地区), 2020 census — GSI layer did2020",
  "sourceUrl": "https://cyberjapandata.gsi.go.jp/xyz/did2020/{z}/{x}/{y}.png",
  "regime": "Civil Aeronautics Act — unmanned flight over a DID requires the Minister's permission",
  "kind": "permission",
  "basis": "raster-sampled",
  "effective": "2020 census",
  "sampled": "2026-07-26",
  "sampledCells": 5688,
  "cellsRequiringPermission": 5688,
  "coveragePct": 100
};
