/**
 * Position bookmarks — saved FENs the user wants to revisit.
 *
 * Persisted to localStorage; max 30 to keep things manageable. Each bookmark
 * gets an autogenerated label from the FEN (move number + side to move) plus
 * an optional user note. Designed to be wired into the Command Palette so
 * any saved position is one Ctrl+K + label-search away.
 */

const KEY = "aevion_chess_bookmarks_v1";
const MAX = 30;

export type Bookmark = {
  id: string;
  fen: string;
  label: string;     // user-visible name
  note?: string;     // optional memo
  ts: number;        // saved at
};

export function loadBookmarks(): Bookmark[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(KEY);
    if (!raw) return [];
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr : [];
  } catch { return []; }
}

export function saveBookmarks(bs: Bookmark[]): void {
  try { localStorage.setItem(KEY, JSON.stringify(bs.slice(0, MAX))); } catch {}
}

/**
 * Adds a bookmark. Returns the new list. If the FEN already exists it's
 * moved to the top instead of duplicated.
 */
export function addBookmark(list: Bookmark[], fen: string, label?: string, note?: string): Bookmark[] {
  const existing = list.findIndex(b => b.fen === fen);
  const bm: Bookmark = {
    id: `bm-${Date.now().toString(36)}`,
    fen,
    label: label || autoLabel(fen),
    note,
    ts: Date.now(),
  };
  const filtered = existing >= 0 ? list.filter((_, i) => i !== existing) : list;
  const next = [bm, ...filtered].slice(0, MAX);
  saveBookmarks(next);
  return next;
}

export function removeBookmark(list: Bookmark[], id: string): Bookmark[] {
  const next = list.filter(b => b.id !== id);
  saveBookmarks(next);
  return next;
}

/** Friendly label from FEN: "Ход 12 · ход чёрных" */
function autoLabel(fen: string): string {
  try {
    const parts = fen.trim().split(/\s+/);
    const side = parts[1] === "w" ? "ход белых" : "ход чёрных";
    const move = parts[5] || "?";
    return `Ход ${move} · ${side}`;
  } catch {
    return "Закладка";
  }
}
