#!/usr/bin/env node
/**
 * AEVION coord-doc auto-updater.
 *
 * Reads `git log` for the last N minutes (default 10), groups commits by
 * branch, and writes a fresh "WIP — last N min activity" table into
 * `AEVION_COORDINATION.md` between two marker lines:
 *
 *   <!-- WIP-AUTO:BEGIN -->
 *   …generated content…
 *   <!-- WIP-AUTO:END -->
 *
 * The rest of the coord-doc is untouched. Idempotent — safe to run on a
 * 5-minute timer from any session. Recommended cadence per the
 * 2026-05-12 user-mandated WIP rule (`feedback_coord_doc_5min_wip`).
 *
 * Usage:
 *   node scripts/coord-update.js                # 10-min window
 *   WIP_WINDOW_MIN=5 node scripts/coord-update.js
 *
 * The script does NOT commit or push — that's intentional. Each session
 * commits the doc with their own coordinator commit so attribution is
 * clear. The wrapper `npm run coord:update` just regenerates the table;
 * a follow-up wrapper can `git commit --only -- AEVION_COORDINATION.md`
 * if desired.
 */

const fs = require("node:fs");
const path = require("node:path");
const { execSync } = require("node:child_process");

const REPO = path.resolve(__dirname, "..", "..");
const DOC = path.join(REPO, "AEVION_COORDINATION.md");
const BEGIN = "<!-- WIP-AUTO:BEGIN -->";
const END = "<!-- WIP-AUTO:END -->";
const WINDOW_MIN = Number(process.env.WIP_WINDOW_MIN || 10);

function sh(cmd) {
  return execSync(cmd, { cwd: REPO, encoding: "utf8" }).trim();
}

function fetchRecent() {
  // %H %cI %cr %D %s  — hash, commit ISO, relative, refs, subject
  const sep = "";
  const fmt = ["%H", "%cI", "%cr", "%D", "%s"].join(sep);
  const raw = sh(`git log --all --since="${WINDOW_MIN} minutes ago" --pretty=format:"${fmt}"`);
  if (!raw) return [];
  return raw.split("\n").map((line) => {
    const [hash, iso, rel, refs, subject] = line.split(sep);
    return { hash, iso, rel, refs: (refs || "").trim(), subject: (subject || "").trim() };
  });
}

function worktreeMap() {
  const raw = sh("git worktree list --porcelain");
  const map = new Map();
  const blocks = raw.split("\n\n");
  for (const b of blocks) {
    let wt = ""; let br = "";
    for (const ln of b.split("\n")) {
      if (ln.startsWith("worktree ")) wt = ln.slice(9).trim();
      if (ln.startsWith("branch ")) br = ln.slice(7).replace("refs/heads/", "").trim();
    }
    if (br) map.set(br, wt.replace(REPO + path.sep, "").replace(REPO, "") || "(this repo)");
  }
  return map;
}

function pickBranch(refs) {
  if (!refs) return "(detached)";
  const parts = refs.split(",").map((s) => s.trim());
  for (const p of parts) {
    if (p.startsWith("HEAD ->")) return p.slice(7).trim();
    if (p === "HEAD") continue;
    if (p.startsWith("origin/")) continue;
    if (p.startsWith("tag:")) continue;
    return p;
  }
  // Fallback: pick the first origin/ ref so the row is still informative.
  for (const p of parts) if (p.startsWith("origin/")) return p;
  return "(unknown)";
}

function modulePrefix(subject) {
  const m = subject.match(/^[a-z]+\(([^)]+)\):/i);
  return m ? m[1] : "—";
}

function render(commits, wtMap) {
  const now = new Date().toISOString();
  if (commits.length === 0) {
    return [
      BEGIN,
      `<!-- regenerated ${now} — empty window -->`,
      "",
      `### WIP — last ${WINDOW_MIN} min activity`,
      "",
      `_No commits in the last ${WINDOW_MIN} minutes. Updated ${now}._`,
      "",
      END,
    ].join("\n");
  }

  // Group by branch
  const byBranch = new Map();
  for (const c of commits) {
    const b = pickBranch(c.refs);
    if (!byBranch.has(b)) byBranch.set(b, []);
    byBranch.get(b).push(c);
  }

  const rows = [];
  for (const [branch, list] of [...byBranch.entries()].sort()) {
    list.sort((a, b) => (a.iso < b.iso ? 1 : -1));
    const wt = wtMap.get(branch) || "(no worktree)";
    const mods = [...new Set(list.map((c) => modulePrefix(c.subject)))].filter((m) => m !== "—").slice(0, 5).join(", ") || "—";
    const lastIso = list[0].iso;
    const lastRel = list[0].rel;
    const lastShort = list[0].subject.length > 80 ? list[0].subject.slice(0, 77) + "…" : list[0].subject;
    rows.push(`| \`${branch}\` | ${wt || "—"} | ${list.length} | ${mods} | ${lastRel} | ${lastShort} |`);
  }

  return [
    BEGIN,
    `<!-- regenerated ${now} — window=${WINDOW_MIN}min commits=${commits.length} branches=${byBranch.size} -->`,
    "",
    `### WIP — last ${WINDOW_MIN} min activity`,
    "",
    `_Auto-generated by \`scripts/coord-update.js\`. Re-run \`npm run coord:update\` every 5 min during active work (per \`feedback_coord_doc_5min_wip\`)._`,
    "",
    `| Branch | Worktree | Commits | Modules | Last | Subject |`,
    `|---|---|---:|---|---|---|`,
    ...rows,
    "",
    `_Last refresh: ${now}_`,
    "",
    END,
  ].join("\n");
}

function main() {
  if (!fs.existsSync(DOC)) {
    console.error(`coord doc not found at ${DOC}`);
    process.exit(2);
  }
  const commits = fetchRecent();
  const wtMap = worktreeMap();
  const block = render(commits, wtMap);

  let doc = fs.readFileSync(DOC, "utf8");
  if (doc.includes(BEGIN) && doc.includes(END)) {
    const before = doc.split(BEGIN)[0];
    const after = doc.split(END)[1];
    doc = before + block + after;
  } else {
    // First run — append at the very top, right after the H1.
    const lines = doc.split("\n");
    let insertAt = 1;
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith("# ")) { insertAt = i + 1; break; }
    }
    lines.splice(insertAt, 0, "", block, "");
    doc = lines.join("\n");
  }
  fs.writeFileSync(DOC, doc);
  console.log(`Wrote WIP section: ${commits.length} commits across ${new Set(commits.map((c) => pickBranch(c.refs))).size} branches (window=${WINDOW_MIN}min)`);
}

main();
