/**
 * Splits the translation dictionary into one module per language.
 *
 * Why: `i18n-data.ts` held all eleven dictionaries in one object, and the
 * client provider imports it, so every page of the platform shipped every
 * language. Measured 10.08.2026 with scripts/page-weight.mjs, that chunk was
 * 1.3 MB of the 2.5 MB a page must load before it can answer a tap — the single
 * biggest item, and eleven times more than a person can read.
 *
 * Reads the dictionary AT RUNTIME, not as source text. This is the correction
 * to the first attempt: the file filled eight languages in below the literal
 * via `Object.assign`, so `translations.ru` held 7222 keys while its literal
 * showed 3888. A split that reads the text alone silently drops most of the
 * dictionary, including every key French has.
 *
 * Run from `frontend/`, pointing at whatever module still exports the whole
 * dictionary:
 *
 *   node scripts/splitI18n.mjs ../src/lib/i18n-data.ts
 *
 * This ran once, on 10.08.2026, to move the data out of `i18n-data.ts`. The
 * generated files are committed and are the dictionary from then on — edits go
 * into them directly, and there is nothing left to re-split. The script stays
 * as the record of how the strings got where they are, and in case another
 * aggregate ever needs the same treatment.
 */

import { writeFile, mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const OUT_DIR = path.join(HERE, "..", "src", "lib", "i18n-lang");

/** The module text written for one language — data only, no logic. */
export function moduleFor(lang, dict) {
  const entries = Object.entries(dict)
    // Sorted so a re-run produces a stable file and a diff shows real changes,
    // not a reshuffle.
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");

  return (
    `// Generated by scripts/splitI18n.mjs — one language per file, so a page\n` +
    `// ships the dictionary it needs instead of all eleven. Edit freely: this\n` +
    `// file is the dictionary, not a copy of one.\n` +
    `const ${lang}: Record<string, string> = {\n${entries}\n};\n\nexport default ${lang};\n`
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const from = process.argv[2] || "../src/lib/i18n-data.ts";
  const { LANGS, translations } = await import(from.startsWith(".") ? from : path.resolve(from));
  if (!translations) throw new Error(`${from} exports no translations — nothing to split`);

  await mkdir(OUT_DIR, { recursive: true });

  for (const lang of LANGS) {
    const text = moduleFor(lang, translations[lang]);
    await writeFile(path.join(OUT_DIR, `${lang}.ts`), text, "utf8");
    console.log(`${lang}: ${Object.keys(translations[lang]).length} keys, ${Math.round(text.length / 1024)} KB`);
  }

  console.log(`${LANGS.length} languages written to ${OUT_DIR}`);
}
