/**
 * Splits the single 2.4 MB translations object into one module per language.
 *
 * Why: `i18n-data.ts` is imported by `I18nProvider` from the root layout, so
 * every page of the platform ships all eleven dictionaries. Measured 28.07.2026
 * on a mid-range phone (CPU x6, 1.6 Mbps), the DevHub shelf paints at 6.9s and
 * answers its first tap at 18.7s; 55 JS files, 6.7 MB decompressed. Kazakh
 * alone is 1.68 MB of that, and a person needs exactly one language.
 *
 * This file only rearranges — it never edits a translation. `splitTranslations`
 * is exported separately from the writing so a test can prove, against the real
 * dictionary, that the pieces reassemble into the original with nothing lost,
 * added, or altered.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const SOURCE = path.join(HERE, "..", "src", "lib", "i18n-data.ts");
export const OUT_DIR = path.join(HERE, "..", "src", "lib", "i18n-lang");

/**
 * Finds each top-level language block inside `export const translations = {`
 * by tracking brace depth, so a `{` inside a translated string cannot fool it.
 * Returns { lang: "<the object literal, braces included>" }.
 */
export function splitTranslations(source) {
  const anchor = source.indexOf("export const translations = {");
  if (anchor < 0) throw new Error("translations object not found");
  const objectStart = source.indexOf("{", anchor);

  const blocks = {};
  let i = objectStart + 1;
  let inString = null;

  while (i < source.length) {
    const ch = source[i];

    if (inString) {
      if (ch === "\\") { i += 2; continue; }
      if (ch === inString) inString = null;
      i++;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") { inString = ch; i++; continue; }
    if (ch === "}") break; // end of the translations object itself

    // A language key: `de: {` or `"de": {`
    const key = /^\s*"?([a-z]{2})"?\s*:\s*\{/.exec(source.slice(i, i + 24));
    if (!key) { i++; continue; }

    const bodyStart = source.indexOf("{", i);
    let depth = 0;
    let j = bodyStart;
    let str = null;
    for (; j < source.length; j++) {
      const c = source[j];
      if (str) {
        if (c === "\\") { j++; continue; }
        if (c === str) str = null;
        continue;
      }
      if (c === '"' || c === "'" || c === "`") { str = c; continue; }
      if (c === "{") depth++;
      else if (c === "}") { depth--; if (depth === 0) break; }
    }
    if (depth !== 0) throw new Error(`unbalanced braces in "${key[1]}"`);

    blocks[key[1]] = source.slice(bodyStart, j + 1);
    i = j + 1;
  }

  if (Object.keys(blocks).length === 0) throw new Error("no language blocks found");
  return blocks;
}

/** The module text written for one language — data only, no logic. */
export function moduleFor(lang, body) {
  return `// Generated by scripts/splitI18n.mjs from i18n-data.ts — do not edit by hand.\n` +
    `// One language per file so a page ships only the dictionary it needs.\n` +
    `const ${lang}: Record<string, string> = ${body};\n\nexport default ${lang};\n`;
}

// Running the file writes the modules; importing it does not.
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  const source = await readFile(SOURCE, "utf8");
  const blocks = splitTranslations(source);
  await mkdir(OUT_DIR, { recursive: true });
  for (const [lang, body] of Object.entries(blocks)) {
    await writeFile(path.join(OUT_DIR, `${lang}.ts`), moduleFor(lang, body), "utf8");
    console.log(`${lang}: ${Math.round(body.length / 1024)} KB`);
  }
  console.log(`\n${Object.keys(blocks).length} languages written to ${OUT_DIR}`);
}
