export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 text-gray-200">
      <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
      <p className="text-gray-400 text-sm mb-10">Last updated: May 19, 2026</p>

      <section className="space-y-6 text-sm leading-relaxed">
        <div>
          <h2 className="text-lg font-semibold text-white mb-2">1. Information We Collect</h2>
          <p>We collect information you provide directly (name, email, payment details) and information generated by your use of the Service (usage data, logs, preferences).</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">2. How We Use Your Information</h2>
          <ul className="list-disc list-inside space-y-1 text-gray-300">
            <li>To provide and improve the Service</li>
            <li>To process payments via Paddle (our Merchant of Record)</li>
            <li>To send transactional emails and service updates</li>
            <li>To comply with legal obligations</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">3. Payment Processing</h2>
          <p>All payments are processed by Paddle.com, who acts as the Merchant of Record. AEVION does not store your payment card details. Paddle's privacy policy applies to payment data: <a href="https://www.paddle.com/legal/privacy" className="text-blue-400 hover:underline" target="_blank" rel="noopener noreferrer">paddle.com/legal/privacy</a></p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">4. Data Sharing</h2>
          <p>We do not sell your personal data. We share data only with service providers necessary to operate the Service (hosting, analytics, payment processing) under confidentiality agreements.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">5. Data Retention</h2>
          <p>We retain your data for as long as your account is active or as needed to provide services. You may request deletion of your account and associated data at any time.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">6. Your Rights</h2>
          <p>You have the right to access, correct, or delete your personal data. To exercise these rights, contact us at <a href="mailto:privacy@aevion.app" className="text-blue-400 hover:underline">privacy@aevion.app</a></p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">7. Cookies</h2>
          <p>We use essential cookies for authentication and preferences. We do not use third-party advertising cookies.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">8. Security</h2>
          <p>We implement industry-standard security measures including encryption in transit (HTTPS) and at rest. No method of transmission over the internet is 100% secure.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-white mb-2">9. Contact</h2>
          <p>For privacy-related questions: <a href="mailto:privacy@aevion.app" className="text-blue-400 hover:underline">privacy@aevion.app</a></p>
        </div>
      </section>
    </div>
  );
}
